alias gs="git status"
alias glo="git log --all --decorate --graph --oneline"
alias gc="git checkout"
alias gcam="git commit -am"
alias gpom="git push origin master"
alias glom="git pull origin master"
alias gpomt="git push origin master && git push origin --tags"
